# Generated by Django 5.2.8 on 2025-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GR', 'Groceries'), ('LE', 'Leisure'), ('EL', 'Electronics'), ('UT', 'Utilities'), ('CL', 'Clothing'), ('HE', 'Health'), ('OT', 'Others')], default='OT', max_length=2)),
            ],
        ),
    ]
